# moveit/moveit:melodic-ci
# Sets up a base image to use for running Continuous Integration on Travis

FROM osrf/ros2:bouncy-ros-base
MAINTAINER Lander Usategui  lander@erlerobotics.com

# Setup ROS2 workspace
RUN mkdir -p ros2_ws/src
WORKDIR ros2_ws
